api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from fire_alert_core.views import RegisterView, ChangePasswordView
from user_profile.views import ProfileView, RequestPasswordResetEmail, UploadIDPhotoView, UploadPhotoView
from carousel_image.views import CarouselImageView
from fire_guard.views import FireAlertServicesView
app_name = 'api'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('forgot-password', RequestPasswordResetEmail.as_view(),
         name='forgot-password '),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
    path('upload-photo/<pk>', UploadPhotoView.as_view(), name='upload-photo'),


    path('upload-id-photo/<pk>', UploadIDPhotoView.as_view(), name='upload-id-photo'),
    path('change-password', ChangePasswordView.as_view(), name='change-password'),
    path('carousel', CarouselImageView.as_view(), name='carousel'),
    path('fire-guard', FireAlertServicesView.as_view(), name='fire-guard'),
]

fire_alert_core/urls.py
from django.contrib import admin
from django.urls import path
from drf_yasg import openapi
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import TokenViewWithUserId
from user_profile.views import UserViewSet
from rest_framework.routers import DefaultRouter
from django.conf import settings
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from front_end.views import login_view, home, refresh_home, refresh_queue

schema_view = get_schema_view(
    openapi.Info(
        title="Fire alert hub API",
        default_version='v1',
        description="Testing API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register("user", UserViewSet, basename="user")
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
    path('api-auth/', include('rest_framework.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('o/login/', TokenViewWithUserId.as_view(), name='token'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('services/', include('front_end.urls', namespace='services')),
    path('login', login_view, name='login'),
    path('', home, name='home'),
    path('refresh-home', refresh_home, name='refresh-home'),
    path('refresh-queue', refresh_queue, name='refresh-queue'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),

]
urlpatterns += router.urls
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front_end/urls.py
from django.urls import path

from .views import on_going, completed, rejected, edit_report_view, queue, history_report
app_name = 'services'

urlpatterns = [
    path('on-going', on_going, name='on_going'),
    path('queue', queue, name='queue'),
    path('completed', completed, name='completed'),
    path('rejected', rejected, name='rejected'),
    path('edit-report-view/<pk>', edit_report_view, name='edit_report_view'),
    path('history_report', history_report, name='history_report'),
]

front_end/models.py
from django.db import models

# Create your models here.

front_end/forms.py
from django.forms import ModelForm
from fire_guard.models import FireAlertServices


class FireAlertServicesForm(ModelForm):
    class Meta:
        model = FireAlertServices
        fields = ['sender', 'address', 'google_map_url',
                  'message', 'longitude', 'latitude', 'incident_type',
                  'is_accepted', 'is_done', 'is_rejected', 'image', 'video'
                  ]

        readonly_fields = ['image', 'video']

front_end/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from fire_guard.models import FireAlertServices
from .forms import FireAlertServicesForm


def login_view(request):
    msg_error = ""

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None and user.is_superuser:
            login(request, user)
            return redirect('home')
        else:
            msg_error = "email and password didn't match"

    return render(request, 'front_end/login.html', {'error': msg_error})


@login_required(login_url='login')
def home(request):

    queues = FireAlertServices.objects.filter(
        is_accepted=False, is_done=False, is_rejected=False).order_by("-date_created")
    total_queue = queues.count()
    total_on_going = FireAlertServices.objects.filter(
        is_accepted=True, is_done=False, is_rejected=False).count()
    total_completed = FireAlertServices.objects.filter(
        is_accepted=True, is_done=True, is_rejected=False).count()
    total_rejected = FireAlertServices.objects.filter(is_rejected=True).count()

    context = {
        "total_queue": total_queue,
        "total_on_going": total_on_going,
        "total_completed": total_completed,
        "total_rejected": total_rejected,
        "queues": "queues"
    }

    return render(request, 'front_end/home.html', context)


@login_required(login_url='login')
def on_going(request):

    queues = FireAlertServices.objects.filter(
        is_accepted=True, is_done=False).order_by("-date_created")

    return render(request, 'front_end/on_going.html', {'queues': queues})


@login_required(login_url='login')
def completed(request):

    queues = FireAlertServices.objects.filter(
        is_accepted=True, is_done=True, is_rejected=False).order_by("-date_created")

    return render(request, 'front_end/completed.html', {'queues': queues})


@login_required(login_url='login')
def rejected(request):

    queues = FireAlertServices.objects.filter(
        is_rejected=True).order_by("-date_created")

    return render(request, 'front_end/rejected.html', {'queues': queues})


@login_required(login_url='login')
def refresh_home(request):

    queues = FireAlertServices.objects.filter(
        is_accepted=False, is_done=False, is_rejected=False).order_by("-date_created")
    total_queue = queues.count()
    total_on_going = FireAlertServices.objects.filter(
        is_accepted=True, is_done=False, is_rejected=False).count()
    total_completed = FireAlertServices.objects.filter(
        is_accepted=True, is_done=True, is_rejected=False).count()
    total_rejected = FireAlertServices.objects.filter(is_rejected=True).count()

    context = {
        "total_queue": total_queue,
        "total_on_going": total_on_going,
        "total_completed": total_completed,
        "total_rejected": total_rejected,
        "queues": "queues"
    }

    return render(request, 'front_end/home_queue_hidden.html', context)


@login_required(login_url='login')
def edit_report_view(request, pk):
    service = get_object_or_404(FireAlertServices, pk=pk)
    form = FireAlertServicesForm(instance=service)

    if request.POST:
        form = FireAlertServicesForm(request.POST, instance=service)

        if form.is_valid():
            form.save()

    url = f'http://www.google.com/maps/place/{service.latitude},{service.longitude}'
    data = {
        'form': form,
        'pk': pk,
        'url': url,
    }

    return render(request, 'front_end/edit_form.html', data)


@login_required(login_url='login')
def queue(request):

    queues = FireAlertServices.objects.filter(
        is_accepted=False, is_done=False).order_by("-date_created")

    return render(request, 'front_end/queue_page.html', {'queues': queues})


@login_required(login_url='login')
def refresh_queue(request):

    queues = FireAlertServices.objects.filter(
        is_accepted=False, is_done=False, is_rejected=False).order_by("-date_created")

    return render(request, 'front_end/queue.html', {'queues': queues})


@login_required(login_url='login')
def history_report(request):

    queues = FireAlertServices.objects.all().order_by("-date_created")
    return render(request, 'front_end/history.html', {'queues': queues})

templates/front_end/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>FireGuard</title>
  </head>
  <body>
    <main>
        {% block content %}

        {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      {% block extrascripts %}{% endblock extrascripts %}

  </body>
</html>

templates/front_end/completed.html
{% extends 'front_end/base.html' %}
{% load static %}
{% block content %}

    {% include 'front_end/navigation_bar.html' %}
    <input type="hidden" id="queue" value="{% url 'refresh-home' %}">

    <div class="container-fluid p-2">
        <div class="d-flex align-items-center justify-content-center">
            <p class="h1"> Completed </p>
        </div>
        {% include 'front_end/queue.html' %}
    </div>

{% endblock %}

templates/front_end/edit_form.html
{% extends 'front_end/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    {% include 'front_end/navigation_bar.html' %}
    <input type="hidden" id="queue" value="{% url 'refresh-home' %}">

    <div class="container-fluid p-2">
        <form method="POST" action="{% url 'services:edit_report_view' pk %}" >
        {% csrf_token %}
            <div class="mb-3">
                <a href="{{ url }}" target=”_blank”>
                    <p class="h2">Click to open google map</p>
                </>
            </div>
            {{ form|crispy}}
            <div class="mb-3 text-center">
                <button type="submit" class="btn btn-primary">SUBMIT</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/front_end/history.html
{% extends 'front_end/base.html' %}
{% load static %}
{% block content %}

{% include 'front_end/navigation_bar.html' %}

<div class="container-fluid p-2">
    <div class="col d-flex justify-content-center align-items-center mb-4">
        <img src="https://i.ibb.co/bK6wkYd/brand.jpg" class="rounded-circle" alt="..." style="height: 15rem; width: 15rem;">
    </div>
    <table class="table  table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col" style="width:20%">Name</th>
                <th scope="col" style="width:20%">Type of Incident</th>
                <th scope="col" style="width:15%">Status</th>
                <th scope="col" style="width:15%">Date</th>
                <th scope="col" style="width:10%">Image</th>
                <th scope="col" style="width:10%">Video</th>
            </tr>
        </thead>
        <tbody>

            {% for queue in queues %}

            <tr>
                <th role="button" data-href="{% url 'services:edit_report_view' queue.pk %}" style="cursor: pointer;"
                    scope="row">{{ forloop.counter }}</th>
                <td role="button" data-href="{% url 'services:edit_report_view' queue.pk %}" style="cursor: pointer;">
                    {{queue.sender.user.first_name}}
                </td>
                <td>{{queue.incident_type}}</td>
                <td>

                    {% if queue.is_rejected %}
                    <button type="button" class="btn btn-danger">
                        Rejected</button>


                    {% elif queue.is_done and queue.is_accepted %}
                    <button type="button" class="btn btn-warning">
                        Rescued</button>

                    {% elif queue.is_accepted and not queue.is_done %}

                    <button type="button" class="btn btn-secondary">
                        On going</button>
                    {% else %}
                    <button type="button" class="btn btn-primary">
                        Queue</button>

                    {% endif %}
                </td>
                <td>
                    {{queue.date_created}}
                </td>
                <td>
                    {% if queue.image %}
                    <a type="button" class="btn btn-primary" role="button" href="{{queue.image.url}}" target=”_blank”>
                        View Image
                    </a>
                    {% endif %}
                </td>
                <td>
                    {% if queue.video %}
                    <a type="button" class="btn btn-info" role="button" href="{{queue.video.url}}" target=”_blank”>
                        View Video
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}


        </tbody>
    </table>
</div>

{% endblock %}



{% block extrascripts %}
<script type="text/javascript">
    $(function () {
        $(".table").on("click", "th[role=\"button\"]", function (e) {
            window.location = $(this).data("href");
        });
    });
</script>

{% endblock extrascripts %}

templates/front_end/home.html
{% extends 'front_end/base.html' %}
{% load static %}
{% block content %}

{% include 'front_end/navigation_bar.html' %}
<audio id="soundEffect" autoplay controls>
    <source src="{% static 'sound/sound.mp3' %}" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>
<input type="hidden" id="queue" value="{% url 'refresh-home' %}">
        {% include 'front_end/home_queue_hidden.html' %}
</div>



{% endblock %}
{% block extrascripts %}
<script type="text/javascript">
    var numItems = $('#totalQueue').text();

    console.log(numItems);
    function myFunction() {
        var x = document.getElementById("notif");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }

    function refresh() {
        var url = document.getElementById('queue').value

        $.ajax({
            url: url,
            type: 'GET',
            success: function (data) {
                $("#queueResult").html(data);
                var tempNumItems = $('#totalQueue').text();

                console.log(numItems);
                console.log(tempNumItems);

                if (numItems < tempNumItems && tempNumItems > 0) {
                    numItems = tempNumItems;
                    myFunction();
                    sound = document.getElementById('soundEffect');
                    sound.currentTime = 0;
                    sound.play();
                }
             setTimeout(refresh, 10000);
        
            }
        });
    }

    $(function () {
        refresh()
    });
</script>
{% endblock extrascripts %}

templates/front_end/home_queue_hidden.html
<div id="queueResult">
<div class="container-fluid p-2">
    <div class="row">
        <div class="col-sm-6 py-4">
            <a href="{% url 'services:queue' %}" style="color: black;">
                <div class="card" style="background-color: #F9EE98;">
                    <div class="card-body" style="height: 10rem;">
                        <h5 class="card-title">QUEUE</h5>
                        <p id="totalQueue" class="card-text text-center h3">{{total_queue}}</p>
                    </div>
                </div>
            </a>

        </div>
        <div class="col-sm-6 py-4">
            <a href="{% url 'services:on_going' %}" style="color: black;">
                <div class="card" style="background-color: #F9EE98;">
                    <div class="card-body " style="height: 10rem;">
                        <h5 class="card-title">ON GOING</h5>
                        <p class="card-text text-center h3">{{total_on_going}}</p>
                    </div>
                </div>
            </a>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 py-4">
            <a href="{% url 'services:completed' %}" style="color: black;">
                <div class="card" style="background-color: #F9EE98;">
                    <div class="card-body card-block " style="height: 10rem;">
                        <h5 class="card-title">COMPLETED</h5>
                        <p class="card-text text-center h3">{{total_completed}}</p>
                    </div>
                </div>
            </a>

        </div>

        <div class="col-sm-6 py-4">
            <a href="{% url 'services:rejected' %}" style="color: black;">
                <div class="card" style="background-color: #F9EE98;">
                    <div class="card-body card-block " style="height: 10rem;">
                        <h5 class="card-title">REJECTED</h5>
                        <p class="card-text text-center h3">{{total_rejected}}</p>
                    </div>
                </div>
            </a>

        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6 py-4">
            <a href="{% url 'services:history_report' %}" style="color: black;">
                <div class="card card-block" style="height: 10rem; background-color: #F9EE98;">
                    <div class="card-body d-flex justify-content-center align-items-center">
                        <h5 class="card-text text-center">HISTORY OF THE REPORTS</h5>
                    </div>
                </div>
            </a>
        </div>
    </div>
        <div id="notif" class="card alert-fixed" style="display: none;">
        <div class="card-header">
            🚨Emergency Report
        </div>
        <div class="card-body">
            <p class="card-text">There is an emergency reported at this moment.
                Immediate attention required. Your cooperation is important for an efficient response!
            </p>
            <div class="row">
                <div class="col-sm">
                    <a href="#" class="btn btn-danger" onclick="myFunction()">Close</a>
                </div>
                <div class="col-sm">
                    <a href="{% url 'services:queue' %}" class="btn btn-primary">View Report</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/front_end/login.html
{% extends 'front_end/base.html' %}
{% block content %}

<div class="h-100 d-flex align-items-center justify-content-center mt-4 p-4">
    <div class="col-sm-12 col-lg-6">
        <form class="g-3" action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <p>LOGIN</p>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="form-label">Email address</label>
                <input type="email" class="form-control" name="username" id="exampleFormControlInput1"
                    placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label for="inputPassword5" class="form-label">Password</label>
                <input type="password" id="inputPassword5" name="password" class="form-control"
                    aria-labelledby="passwordHelpBlock">
            </div>

            {% if error %}
            <div class="mb-3">
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            </div>


            {% endif %}
            <div class="mb-3 text-center">
                <button type="submit" class="btn btn-primary">SUBMIT</button>
            </div>

        </form>
    </div>

</div>
{% endblock %}

templates/front_end/navigation_bar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">
    <div class="row">
    FireGuard

            <img src="https://i.ibb.co/bK6wkYd/brand.jpg" class="rounded-circle ml-2" alt="..." style="height: 2rem; width: 2rem;">

    </div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'services:queue' %}">Queue</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'services:on_going' %}">On going</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'services:completed' %}">Completed</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'services:rejected' %}">Rejected</a>
      </li>
    </ul>
    <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Logout</button>
  </div>
</nav>

templates/front_end/on_going.html
{% extends 'front_end/base.html' %}
{% load static %}
{% block content %}

    {% include 'front_end/navigation_bar.html' %}
    <input type="hidden" id="queue" value="{% url 'refresh-home' %}">

    <div class="container-fluid p-2">
        <div class="d-flex align-items-center justify-content-center">
            <p class="h1"> On Going </p>
        </div>
        {% include 'front_end/queue.html' %}
    </div>

{% endblock %}

templates/front_end/queue.html
<div id="queueResult" class="list-group">
    {% for queue in queues %}
        <a href="{% url 'services:edit_report_view' queue.pk %}" class="list-group-item list-group-item-action">{{ queue }}</a>
    {% endfor %}
</div>

templates/front_end/queue_page.html
{% extends 'front_end/base.html' %}
{% load static %}
{% block content %}

    {% include 'front_end/navigation_bar.html' %}
    <input type="hidden" id="queue" value="{% url 'refresh-queue' %}">

    <div class="container-fluid p-2">
        <div class="d-flex align-items-center justify-content-center">
            <p class="h1"> Queue </p>
        </div>
        {% include 'front_end/queue.html' %}
    </div>

{% endblock %}
{% block extrascripts %}
    <script type="text/javascript">


		function refresh() {
			var url = document.getElementById('queue').value

			$.ajax({
				url: url,
				type: 'GET',
				success: function (data) {
                    $("#queueResult").html(data);
				}
			});
			setTimeout(refresh, 10000);
		}

		$(function () {
			refresh();
		});
	</script>   
	{% endblock extrascripts %}

templates/front_end/rejected.html
{% extends 'front_end/base.html' %}
{% load static %}
{% block content %}

    {% include 'front_end/navigation_bar.html' %}
    <input type="hidden" id="queue" value="{% url 'refresh-home' %}">

    <div class="container-fluid p-2">
        <div class="d-flex align-items-center justify-content-center">
            <p class="h1"> Rejected </p>
        </div>
        {% include 'front_end/queue.html' %}
    </div>

{% endblock %}